### ISSUE TITLE
Will be data be uploaded?

### ISSUE THREAD

**Issue by fynrup** [cyr19/A2T#1]
Hi there, 

I read your paper with great delight and was wondering, if the dataset will be published in the near future?

**Comment by cyr19** [comment]
Thanks. Yes, will do in the following week.


在 2024年2月7日，16:46，Fynn ***@***.***> 写道：

﻿

Hi there,

I read your paper with great delight and was wondering, if the dataset will be published in the near future?

**Comment by cyr19** [comment]
Hi. I uploaded the dataset.
